//peticiones para empleados

###
GET https://miserverlinkedin.herokuapp.com/

###
GET   http://localhost:3000/

###
POST   https://miserverlinkedin.herokuapp.com/send-data
Content-Type: application/json

{
    
    "name":"Edicta Rosa Luzardo", 
    "email":"Edicta48@gmail.com",
    "phone":"04126468685",
    "picture":"somepicture",
    "salary":"700",
    "position":"mi mama"
}

###
POST   http://localhost:3000/send-data
Content-Type: application/json

{
    
    "name":"Andita Mora", 
    "email":"Andita@gmail.com",
    "phone":"041299690527",
    "picture":"somepicture",
    "salary":"500",
    "position":"peluquera"
}

###
POST   http://localhost:3000/delete
Content-Type: application/json

{
    "id":"606002010947d406c42a0fc3"
   
}

###
POST   http://localhost:3000/update
Content-Type: application/json

{
    "id":"606002010947d406c42a0fc3",
    "name":"Alicia ibete Mora Luzardo", 
    "email":"Ali@gmail.com",
    "phone":"041299690527",
    "picture":"somepicture en chile",
    "salary":"500",
    "position":"peluquera"
}
